// admin-onboarding/admin-onboarding-frontend/src/app/pages/login/login.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent {
  email = '';
  password = '';
  showPassword = false;
  loading = false;
  error = '';

  constructor(private auth: AuthService, private router: Router) {}

  togglePassword() { this.showPassword = !this.showPassword; }

  login() {
    if (!this.email || !this.password) { this.error = 'Email and password are required.'; return; }
    this.loading = true;
    this.error = '';
    this.auth.login(this.email, this.password).subscribe({
      next: (res) => {
        this.auth.saveSession(res);
        if (res.requiresPasswordChange) {
          this.router.navigate(['/change-password']);
        } else {
          window.location.href = 'http://localhost:5173';
        }
      },
      error: (err) => {
        this.error = err.error?.error || 'Login failed. Check your credentials.';
        this.loading = false;
      }
    });
  }
}

<div class="auth-bg">
  <div class="auth-card">
    <div class="auth-logo">🛡️</div>
    <h1>Admin Portal Login</h1>
    <p class="auth-sub">Sign in with your administrator credentials</p>

    <div class="error-box" *ngIf="error">{{ error }}</div>

    <form (ngSubmit)="login()">
      <div class="form-group">
        <label>Email Address</label>
        <input
          type="email"
          [(ngModel)]="email"
          name="email"
          placeholder="admin@company.com"
          class="form-control"
          autocomplete="email"
        />
      </div>

      <div class="form-group">
        <label>Password</label>
        <div class="password-wrap">
          <input
            [type]="showPassword ? 'text' : 'password'"
            [(ngModel)]="password"
            name="password"
            placeholder="Enter your password"
            class="form-control"
            autocomplete="current-password"
          />
          <button type="button" class="toggle-btn" (click)="togglePassword()" [title]="showPassword ? 'Hide' : 'Show'">
            {{ showPassword ? '🙈' : '👁️' }}
          </button>
        </div>
      </div>

      <button type="submit" class="btn-primary" [disabled]="loading">
        {{ loading ? 'Signing in...' : 'Sign In' }}
      </button>
    </form>

    <div class="auth-footer">
      <p>New admin? Contact your organisation's onboarding team.</p>
    </div>
  </div>
</div>

// frontend/react-admin-dashboard/src/pages/Login.jsx
import { useState } from 'react'
import { Link } from 'react-router-dom'
import './Login.css'

export default function Login({ onLogin }) {
  const [email, setEmail]       = useState('')
  const [password, setPassword] = useState('')
  const [showPassword, setShowPassword] = useState(false)
  const [error, setError]       = useState('')
  const [loading, setLoading]   = useState(false)

  const handleLogin = async (e) => {
    e.preventDefault()
    setError('')
    setLoading(true)

    try {
      const response = await fetch('/api/auth/login', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json'
        },
        body: JSON.stringify({ email, password })
      })

      const data = await response.json()

      if (!response.ok || data.error) {
        throw new Error(data.error || data.message || 'Login failed')
      }

      if (data.requiresPasswordChange) {
        // If they are logging in with a temporary password, redirect to onboarding portal
        window.location.href = 'http://localhost:4200/change-password'
        return
      }

      // Success
      onLogin(data.token, data)

    } catch (err) {
      setError(err.message || 'Unable to reach authentication server. Please try again.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="login-container">
      <div className="login-card">
        <div className="login-logo">🪐</div>
        <h2>Admin Portal</h2>
        <p>Authenticate to access the dashboard</p>

        {error && <div className="login-error">{error}</div>}

        <form className="login-form" onSubmit={handleLogin}>
          <div>
            <label>Email Address</label>
            <input 
              type="email" 
              placeholder="admin@example.com" 
              value={email}
              onChange={e => setEmail(e.target.value)}
              required 
            />
          </div>
          
          <div>
            <label>Password</label>
            <div className="password-input-wrapper">
              <input 
                type={showPassword ? 'text' : 'password'} 
                placeholder="••••••••" 
                value={password}
                onChange={e => setPassword(e.target.value)}
                required 
              />
              <button 
                type="button" 
                className="show-password-btn"
                onClick={() => setShowPassword(!showPassword)}
                tabIndex="-1"
              >
                {showPassword ? '🙈' : '👁️'}
              </button>
            </div>
            <div style={{ textAlign: 'right', marginTop: '8px' }}>
              <Link to="/forgot-password" style={{ color: '#3b82f6', fontSize: '13px', textDecoration: 'none' }}>
                Forgot Password?
              </Link>
            </div>
          </div>

          <button type="submit" className="login-btn" disabled={loading}>
            {loading ? 'Authenticating...' : 'Sign In'}
          </button>
        </form>

        <div className="login-footer">
          Admins are onboarded internally. No signup available.
        </div>
      </div>
    </div>
  )
}
